language: node_js
node_js:
  - "1.1.0"
before_install:
  - npm install -g bower
  - bower install | xargs echo
  - npm install -g grunt-cli
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

